load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "concept",
    srcs = ["concept.cc"],

    deps = [
        
    ],
    linkopts = [],
    copts = [
        "-std=c++20",
        "-g",
        "-Wall",
    ]
)